export const sliderItems = [
  {
    id: 1,
    img: "https://www.lanoticiaurbana.com/wp-content/uploads/2019/04/donacion-club-florencio-varela.jpg",
    title: "Comedor Almitas Lindas",
    desc: "Reacondicionamiento y equipamiento del comedor",
    bg: "f5fafd",
  },
  {
    id: 2,
    img: "https://salta4400.com/wp-content/uploads/2020/01/45125358394_0898ac1cfe_h.jpg",
    title: "Hospital Publico Materno Infantil ",
    desc: "Colecta para la compra de una ambulancia totalmente equipada ",
    bg: "fcf1ed",
  },
  {
    id: 3,
    img: "https://docplayer.es/docs-images/113/206549008/images/1-0.jpg",
    title: "Bomberos Voluntarios Santo Tome",
    desc: "Compra de motobomba para los bomberos voluntarios de Santo Tome - Corrientes",
    bg: "fbf0f4",  
  },
];
  export const categories = [
    {
      id: 1,
      img: "https://ggsc.s3.amazonaws.com/images/uploads/Adult_and_kid_hands_with_coins.jpg",
      title: "Dona Dinero",
    },
    {
      id: 2,
      img: "https://www.thespruce.com/thmb/bUonOuEXx4lSe7w8djXFwJ8_Puc=/4495x2528/smart/filters:no_upscale()/where-to-donate-everything-in-home-2648117_02-f88c1f8b70324c709dfbd8df9db217c0.jpg",
      title: "Donar Objeto",
    },
    {
      id: 3,
      img: "https://www.clevergirlfinance.com/wp-content/uploads/2021/03/Stop-buying-stuff.jpg",
      title: "Ayuda comprando en el Shop",
    },
  ];

  export const popularProducts = [
    {
      id:1,
      img:"https://www.profesionalreview.com/wp-content/uploads/2018/01/C%C3%B3mo-evitar-el-fondo-negro-al-copiar-un-archivo-PNG-3.jpg",
    },
    {
      id:2,
      img:"https://i2.wp.com/gadwoman.com/wp-content/uploads/2012/04/Monitor-Toshiba.jpg?resize=640%2C400&ssl=1",
    },
    {
      id:3,
      img:"https://i2.wp.com/culturabogota.com/wp-content/uploads/2014/09/sorpresa-fotografo-iphone-6-1.jpg?w=800&ssl=1",
    },
    {
      id:4,
      img:"https://i.blogs.es/f7bb86/650_1000_tele-curva-1/1366_2000.jpg",
    },
    {
      id:5,
      img:"https://images.ecestaticos.com/CmQxEVHJ2Mh7t42OljydEg2iRP8=/0x0:638x359/996x560/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F64f%2F158%2F108%2F64f1581087ce1bc054aede93edb22276.jpg",
    },
    {
      id:6,
      img:"https://http2.mlstatic.com/D_NQ_NP_808163-MLA44585596343_012021-O.webp",
    },
    {
      id:7,
      img:"https://http2.mlstatic.com/D_NQ_NP_823809-MLA48575528008_122021-O.webp",
    },
    {
      id:8,
      img:"https://www.derechoenzapatillas.com/wp-content/uploads/2018/08/cuatriciclos-reglamentaci%C3%B3n.jpg",
    },
  ]

  export const products = [
      {
          id:1,
          fullname:"Buzo Adidas Color Rojo",
          price: 20,
          weight: 1,
          description: "Esta en perfecto estado",
          image:"https://i.ebayimg.com/thumbs/images/g/teMAAOSwYPNcPN~X/s-l225.jpg",
          stock: 1,
          available: true,
      },
      {
        id:2,
        fullname:"Laptop Gamer ASUS ROG",
        price: 550,
        weight: 2,
        description: "Producto brindado por ASUS",
        image:"https://www.profesionalreview.com/wp-content/uploads/2018/01/C%C3%B3mo-evitar-el-fondo-negro-al-copiar-un-archivo-PNG-3.jpg",
        stock: 2,
        available: true,
      },
      {
        id:3,
        fullname:"Monitor Toshiba ACI-77198",
        price: 300,
        weight: 5,
        description: "Un poco descuidado pero funciona bien",
        image:"https://i2.wp.com/gadwoman.com/wp-content/uploads/2012/04/Monitor-Toshiba.jpg?resize=640%2C400&ssl=1",
        stock: 0,
        available: false,
    },
    {
        id:4,
        fullname:"IPhone 6",
        price: 100,
        weight: 2,
        description: "Disponible en diversos colores",
        image:"https://i2.wp.com/culturabogota.com/wp-content/uploads/2014/09/sorpresa-fotografo-iphone-6-1.jpg?w=800&ssl=1",
        stock: 4,
        available: true,
    },
    {
        id:5,
        fullname:"Televisor Curvo Philips XJ-5792",
        price: 450,
        weight: 10,
        description: "Completamente nuevo.",
        image:"https://i.blogs.es/f7bb86/650_1000_tele-curva-1/1366_2000.jpg",
        stock: 1,
        available: true,
    },
    {
        id:6,
        fullname:"Mountain-Bike Licorne",
        price: 560,
        weight: 30,
        description: "",
        image:"https://images.ecestaticos.com/CmQxEVHJ2Mh7t42OljydEg2iRP8=/0x0:638x359/996x560/filters:fill(white):format(jpg)/f.elconfidencial.com%2Foriginal%2F64f%2F158%2F108%2F64f1581087ce1bc054aede93edb22276.jpg",
        stock: 2,
        available: true,
    },
    {
        id:7,
        fullname:"Moto Keller Classic 110",
        price: 980,
        weight: 86,
        description: "Donacion de Motos Keller",
        image:"https://http2.mlstatic.com/D_NQ_NP_808163-MLA44585596343_012021-O.webp",
        stock: 5,
        available: true,
    },
    {
        id:8,
        fullname:"Monopatín Electrico Xiaomi - My Electrical Scooter Essential ",
        price: 730,
        weight: 12,
        description: "Xiaomi Mi Electric Scooter Essential es un nuevo patinete eléctrico color negro y de diseño elegante, desde la luz hasta los neumáticos. Essential está diseñado para las personas que quieren mantenerlo ligero y fácil.",
        image:"https://http2.mlstatic.com/D_NQ_NP_823809-MLA48575528008_122021-O.webp",
        stock: 1,
        available: true,
    },
    {
        id:9,
        fullname:"Cuatriciclo Honda",
        price: 6500,
        weight: 120,
        description: "Este cuatriciclo está preparado para actividades que necesiten gran capacidad de carga, poder y espacio. Su diseño ayuda a desplazarse de una forma más cómoda.",
        image:"https://www.derechoenzapatillas.com/wp-content/uploads/2018/08/cuatriciclos-reglamentaci%C3%B3n.jpg",
        stock: 0,
        available: false,
    },
    {
        id:10,
        fullname:"Remeras Kingdom Vintage Cuello Desbocado Bote Abierto",
        price: 13,
        weight: 0.1,
        description: "",
        image:"https://http2.mlstatic.com/D_NQ_NP_772840-MLA41775603939_052020-O.webp",
        stock: 8,
        available: true,
    },
    {
        id:11,
        fullname:"Mochila Urbana Unisex Sunfin",
        price: 15,
        weight: 0.5,
        description: "Capacidad: 20lts Medidas: 45x30x14.5cm",
        image:"https://http2.mlstatic.com/D_NQ_NP_723203-MLA45838835726_052021-O.webp",
        stock: 2,
        available: true,
    },
    {
        id:12,
        fullname:"Parlante Genius SP-HF180",
        price: 25,
        weight: 7,
        description: "Genius SP-HF180 ofrece un sonido natural, con una gran claridad y precisión, que se dispersa de manera uniforme. Un parlante que asegura potencia y calidad por igual en la reproducción de contenidos multimedia.    ",
        image:"https://http2.mlstatic.com/D_NQ_NP_754878-MLA42899391576_072020-O.webp",
        stock: 1,
        available: true,
    },
    {
        id:13,
        fullname:"Cama elástica Gadnic Pro T8FT",
        price: 275,
        weight: 30,
        description: "Con la cama elástica Gadnic Pro T8FT vas a poder disfrutar de horas interminables de diversión. Saltos y piruetas más los beneficios físicos que genera esta actividad, permitirán que disfrutés de momentos recreativos inolvidables.",
        image:"https://http2.mlstatic.com/D_NQ_NP_838781-MLA49256060024_032022-O.webp",
        stock: 0,
        available: false,
    },
    {
        id:14,
        fullname:"Pantalon Pampero Cargo Antidesgarro Ripstop",
        price: 55,
        weight: 0.5,
        description: "Tela antidesgarro, bolsillos con tapa y velcro y cartera con cierre",
        image:"https://http2.mlstatic.com/D_NQ_NP_738661-MLA42683874698_072020-O.webp",
        stock: 6,
        available: true,
    }
  ]
